apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata: 
  name: <slice-name>
  namespace: kubeslice-<projectname>
spec:
  sliceSubnet: 10.11.0.0/16             #ensure this subnet is not being used in any of the worker clusters
  sliceType: Application
  overlayNetworkDeploymentMode: single-network
  sliceGatewayProvider:
    sliceGatewayType: OpenVPN
    sliceCaType: Local
  sliceIpamType: Local
  clusters:
    - mia-lke
    - gru-lke
    -us-east1-eks
  qosProfileDetails:
    queueType: HTB
    priority: 1                    #keep integer values from 0 to 3
    tcType: BANDWIDTH_CONTROL
    bandwidthCeilingKbps: 50000
    bandwidthGuaranteedKbps: 20000
    dscpClass: AF11
  namespaceIsolationProfile:
    applicationNamespaces:
     - namespace: <app-namespace>
       clusters:
       - '*'
