apiVersion: controller.kubeslice.io/v1alpha1
kind: Cluster
metadata:
  name: gl-mia-lke-01
  namespace: kubeslice-sandbox1
spec:
  clusterProperty:
    geoLocation:
      cloudProvider: "DATACENTER"
      cloudRegion: "eu-central"
---
apiVersion: controller.kubeslice.io/v1alpha1
kind: Cluster
metadata:
  name: gl-gru-lke-01
  namespace: kubeslice-sandbox1
spec:
  clusterProperty:
    geoLocation:
      cloudProvider: "DATACENTER"
      cloudRegion: "eu-central"
