
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUnhwdVVsNC9KdEV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1EVXdNREUwTURGYUZ3MHpOREE1TURNd01ERTVNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURMYVQ4ZFBIa1N4WjRNWUVTWnFqcEY2YVZzb09QTk83QmdpSWlNQzFZVURKWmE0RmcrbkgyWVdkZTYKNUhCMHJqa1RzcjUrMFQvaVEra0hjSDUyQW1qWVVjS3cwT2FKbEhmMGMxdi82WExnNnNraTYrMG05YXZCVXFaTwpaVlBqcWFvYlNZZ21jejFGY0Z6ODdSMm5QK3BnandUd2Y1K0NURmlZNGpVaUlJQjFDUmsrd0NSamQ5UnJRdlhjCmtXRXNGZjJEQ2ZwQjBTR1hJc0dUd3pmZ1JRYmNuMDdaVEtDVUNUMk1WQ0V3d3pQODdiZ3RXUEFaWEkvWHVXR28KT041U3NoNHpQLzYrSHhHMS8vUlZpVDUydHlDVGFnSldxQXZHdTRlL0NVYVc2cTFhUEFHZks1R0RBQXFMellvbgp2aklkUWpuVTFJdXVzKzZnN05yU0ZYNktyeERKQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRcHlTZ1pTT3BRL0FCa0QzR1lVT2ZrdkpmbGZEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTFMZ0ZiY3JmNgpuRFBkT1o2RzlIdGk0SGZ0N3F1Z0lDTWVSdnUxK2JTUGVvRDlBM3VWUXhHdFN0Z3hzbG02emFHT1lJamxHQmlqCms1azM2QjdEZG1ZMHJWcXdkZ0ttL2JkZlRRYkRDZ2pHeUQvNGVZNmZTTjFOS08yR2ptcUVmZDlDOFFOZXcrbGgKcFp1YVVGOTRkMnQwdzRoUWI0bW4zNXJVQ2RPL3lzK2NyOVpLUDIvbkRxUkR0K1BNaVhRNWZtaTEzaGJNWVRIVQpFbUlJdWNuVXZvSHg0Y2FkSjBwQlNkdCtZZ08yWlVybkh2ZkpudDNyOXdETFNya3JMaDZPNE93UFQvZ3JmQzJZCkliT2U1S1VTVm9PNXJqRTNhejlqbzFZS1BEM2R5a010UVF3SVhWeXdpdExJVEdaNSsrUnhOSXY3Q1RHbzdGVk0KdytnSGxJWC9PVzhxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e2b9957a-bdba-40c4-862e-926d4ce87a08.us-mia-2.linodelke.net:443
  name: lke223953

users:
- name: lke223953-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhsTUw1aXdhbmxVRkxvbjd1Z1hfX0NfZUF1eUp1OHlOc1B6QlRzbTdfc0kifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tMnhjeGwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmQ2Y2E3NjQtNzY4NS00OGYyLTljZGMtYjRiM2VhMjhhNTg4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.WCLK9NXlUgHrKlYeeHlNd4lEISVnVIR3T36vzqkTHK0-njt3_rcyiz7NZtRf4UilnyJAsozBc_th8mBEvJMarMgVrcaLflLXt1QG-gHVscM-HpxV8jGNAm5WToIG0g4Js4UvNGxHCbsK2WKKhzqEgPtWbOLQpOSIkeagLpYz1zE_yXZRfvOYQVjilFYepbJlww8HcOehGi1sk5tiea1MiaasoFMuCJ9UjRuBLJkOjpPP4O_r18tc7EsidSw6J4sMYvsmiMzompUh74IXi-CJmWHhburnI7Jq9qWozI6YizpzDDZJdSjOpWfZsIYiaILoLSjvOYmYrkcpxspPivN9ag

contexts:
- context:
    cluster: lke223953
    namespace: default
    user: lke223953-admin
  name: lke223953-ctx

current-context: lke223953-ctx
