apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: server-frontend
          image: gcr.io/google-samples/microservices-demo/frontend:v0.4.1
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-liveness-probe"
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice.boutique.svc.cluster.local:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice.boutique.svc.cluster.local:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice.boutique.svc.cluster.local:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice.boutique.svc.cluster.local:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "adservice.boutique.svc.cluster.local:9555"
            # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
            # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets                                                                  to gcp
            # - name: ENV_PLATFORM
            #   value: "aws"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          # - name: CYMBAL_BRANDING
          #   value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 600m
              memory: 512Mi
      # nodeSelector:
      #   avesha/node-type: "rlautoscaler"
      tolerations:
        - key: "non-app-pods-no-schedule"
          value: "true"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server-cartservice
          image: gcr.io/google-samples/microservices-demo/cartservice:v0.4.1
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "kubeslice-kube-access-demo-pz5g4i.serverless.use1.cache.amazonaws.com:6379,ssl=true"
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command:
                ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command:
                ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
      # nodeSelector:
      #   avesha/node-type: "rlautoscaler"
      tolerations:
        - key: "non-app-pods-no-schedule"
          value: "true"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: default
      containers:
        - name: server-checkoutservice
          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.4.1
          ports:
            - containerPort: 5050
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice.boutique.svc.cluster.local:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice.boutique.svc.cluster.local:50051"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice.boutique.svc.cluster.local:50051"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice.boutique.svc.cluster.local:5000"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice.boutique.svc.cluster.local:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: DISABLE_STATS
              value: "1"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      # nodeSelector:
      #   avesha/node-type: "rlautoscaler"
      tolerations:
        - key: "non-app-pods-no-schedule"
          value: "true"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
